# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit paper.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, error = TRUE)

# pak::pak("EthanSansom/type")
library(type)


## ----eval = FALSE, echo = TRUE------------------------------------------------
# # A list coerced to NA
# mean(list(1, 2, 3))
# #> [1] NA
# 
# # A zero length number coerced to -Inf
# max(numeric())
# #> [1] -Inf
# 
# # Integers coerced to characters
# c(1L, 2L, "A")
# #> [1] "1" "2" "A"


## ----eval = FALSE, echo = TRUE------------------------------------------------
# # Coercing a function to a factor
# as.factor(mean)
# #> Error in `unique.default()`:
# #> ! unique() applies only to vectors
# 
# # Taking the time difference of TRUE and TRUE
# difftime(TRUE, TRUE)
# #> Error in `as.POSIXct.default()`:
# #> ! do not know how to convert 'time1' to class “POSIXct”


## ----eval = FALSE, echo = TRUE------------------------------------------------
# targets::tar_crew <- function(store = targets::tar_config_get("store")) {
#   # Boundary input type validation
#   tar_assert_allow_meta("tar_crew", store)
#   tar_assert_scalar(store)
#   tar_assert_chr(store)
#   tar_assert_nzchar(store)
#   # Implementation...
# }


## ----eval = FALSE, echo = TRUE------------------------------------------------
# sum("A")
# #> Error in `sum()`:
# #> ! invalid 'type' (character) of argument


## ----eval = FALSE, echo = TRUE------------------------------------------------
# base::is.data.frame <- function(x) {
# 	inherits(x, "data.frame")
# }


## ----eval = FALSE, echo = TRUE------------------------------------------------
# x <- function() {}       # Declare `x` as a function
# class(x) <- "data.frame" # Modify the class of `x`
# is.data.frame(x)         # Data frame test passes
# #> [1] TRUE
# 
# # Uses the print.data.frame method
# print(x)
# #> NULL
# #> <0 rows> (or 0-length row.names)


## ----eval = FALSE, echo = TRUE------------------------------------------------
# class(x) <- "Date"
# 
# # Uses the print.Date method
# print(x)
# #> Error in `as.POSIXlt()`:
# #> ! cannot coerce type 'closure' to vector of type 'double'


## ----eval = FALSE, echo = TRUE------------------------------------------------
# t_probability <- t_any |>  # Any object in R
# 	bare_typed("double") |> # With a `typeof()` of "double"
# 	bounded(0, 1, "[]")     # Bounded between 0 and 1 inclusive


## ----eval = FALSE, echo = TRUE------------------------------------------------
# obj_inspect_type(NA_character_, t_string)
# #> Object `NA_character_` does not have the expected type.
# #> v `NA_character_` is a bare <character>.
# #> v `NA_character_` is size 1.
# #> i `NA_character_` must not contain missing elements.
# #> x `NA_character_` is NA at location `1`.


## ----eval = FALSE, echo = TRUE------------------------------------------------
# t_rownames <- type_union(t_int, t_chr) |> complete()
# obj_inspect_type(NA_integer_, t_rownames)
# #> Object `NA_integer_` does not have the expected type.
# #> * Type option 1 of 2:
# #> v `NA_integer_` is a bare <integer>.
# #> i `NA_integer_` must not contain missing elements.
# #> x `NA_integer_` is NA at location `1`.
# #> * Type option 2 of 2:
# #> x `NA_integer_` must be a bare <character>, not a bare <integer>.


## ----eval = FALSE, echo = TRUE------------------------------------------------
# print(t_rownames)
# #> <type_union>
# #> i Type 1 of 2:
# #> * `<object>` is a bare <integer>.
# #> * `<object>` contains no missing values.
# #> i Type 2 of 2:
# #> * `<object>` is a bare <character>.
# #> * `<object>` contains no missing values.


## ----eval = FALSE, echo = TRUE------------------------------------------------
# t_dataframe <- t_any |>
# 	classed("data.frame") |>
# 	has(on_data(), t_list) |>
# 	has(on_each(), t_vec) |>
# 	has(on_attr("row.names"), type_union(t_chr, t_int) |> complete()) |>
# 	has_relation(same_sized(on_each(), on_attr("row.names")))


## ----eval = FALSE, echo = TRUE------------------------------------------------
# # Create a malformed data frame after construction
# obj <- data.frame(x = 1:3, y = c("a", "b", "c"))
# attr(obj, "row.names") <- 1L
# 
# # Later, assert type membership
# obj_assert_type(obj, t_dataframe)
# #> Error in `obj_assert_type()`:
# #> ! Object `obj` is mistyped.
# #> i `obj[["x"]]` and `attr(obj, "row.names")` must be the same size.
# #> x `obj[["x"]]` is size 3 and `attr(obj, "row.names")` is size 1.
# #> i Run last_type() to get the expected type.


## ----eval = FALSE, echo = TRUE------------------------------------------------
# # Constrain the type to further require `id` and `score` columns
# t_survey <- t_dataframe |>
# 	has(on_elm("id"), t_int |> complete()) |>
# 	has(on_elm("score"), t_dbl |> bounded(0, 100))


## ----eval = FALSE, echo = TRUE------------------------------------------------
# t_survey <- dataframe_type(
#   id = t_int |> complete(),
#   score = t_dbl |> bounded(0, 100)
# )
# 
# t_pair <- list_type(x = t_dbl, y = t_dbl)
# 
# t_listof_pair <- list_of_type(t_pair)


## ----eval = FALSE, echo = TRUE------------------------------------------------
# safe_log <- typed(function(x = t_num, base = t_num %:% exp(1)) {
#   log(x, base = base)
# })


## ----eval = FALSE, echo = TRUE------------------------------------------------
# safe_log("ten")
# #> Error in `safe_log()`:
# #> ! Argument `x` is mistyped.
# #> x `x` must be a numeric vector, not the string "ten".
# #> i Run last_type() to get the expected type.


## ----eval = FALSE, echo = TRUE------------------------------------------------
# safe_any <- typed(
#   function(... = t_lgl, na.rm = t_bool %:% FALSE) {
#     any(..., na.rm = na.rm)
#   },
#   returns = t_lgl |> sized(1L)
# )


## ----eval = FALSE, echo = TRUE------------------------------------------------
# na_string <- typed(
#   recyclable(x, na_to),
#   function(x = t_chr, na_to = t_chr |> complete()) {
#     x[is.na(x)] <- na_to
#     x
#   },
#   returns = t_chr |> complete()
# )
# 
# na_string(c("hi", NA, "bye"), na_to = "N/A")
# #> [1] "hi"  "N/A" "bye"
# na_string(c("hi", NA), na_to = character())
# #> Error in `na_string()`:
# #> ! Arguments `x` and `na_to` must be recyclable.
# #> x `x` (size 2) and `na_to` (size 0) are incompatible sizes.


## ----eval = FALSE, echo = TRUE------------------------------------------------
# print(safe_any)
# #> <typed>
# #> function (..., na.rm = FALSE)
# #> {
# #>     any(..., na.rm = na.rm)
# #> }
# #> Arguments:
# #> * Each element of `...` is a bare <logical>.
# #> * `na.rm` is a bare <logical>.
# #> * `na.rm` is size 1.
# #> * `na.rm` contains no missing values.
# #> Returns:
# #> * `<result>` is a bare <logical>.
# #> * `<result>` is size 1.


## ----eval = FALSE, echo = TRUE------------------------------------------------
# # The error does not mention safe_any()
# lapply(list(c(TRUE, FALSE), NA), safe_any, na.rm = "no")
# #> Error in `FUN()`:
# #> ! Argument `na.rm` is mistyped.
# #> x `na.rm` must be a bare <logical>, not a bare <character>.
# #> i Run last_type() to get the expected type.
# 
# # Retrive the full expected type specification
# last_type()
# #> <type>
# #> * `<object>` is a bare <logical>.
# #> * `<object>` is size 1.
# #> * `<object>` contains no missing values.


## ----eval = FALSE, echo = TRUE------------------------------------------------
# fast_any <- untyped(safe_any)
# print(fast_any)
# #> function (..., na.rm = FALSE)
# #> {
# #>     any(..., na.rm = na.rm)
# #> }


## ----eval = FALSE, echo = TRUE------------------------------------------------
# t_int %:% count(0L)
# count <- "A"
# #> Error:
# #> ! Attempted to assign a mistyped value to `count`.
# #> x `<value>` must be a bare <integer>, not a bare <character>.
# #> i Run last_type() to get the expected type.


## ----eval = FALSE, echo = TRUE------------------------------------------------
# const(t_string) %:% version("1.0.0")
# version <- "1.1.0"
# #> Error:
# #> ! Can't assign to the constant `version`.
# #> i Run last_type() to get the expected type.


## ----eval = FALSE, echo = TRUE------------------------------------------------
# # A set of double values
# t_dbl_set <- t_dbl |> complete() |> unduplicated()
# 
# # A labelled vector
# t_labelled <- t_vec |> has(on_attr("label"), t_string)


## ----eval = FALSE, echo = TRUE------------------------------------------------
# t_maybe_dbl_set <- type_union(t_null, t_dbl_set)
# t_listof_dbl_set <- list_of_type(t_dbl_set)


## ----eval = FALSE, echo = TRUE------------------------------------------------
# # Declaring a typed character (typed)
# library(typed)
# Character() ? z <- "A"
# z <- 1L
# #> Error:
# #> ! type mismatch
# #> `typeof(value)`: "integer"
# #> `expected`:      "character"
# 
# # Declaring a typed character (type)
# t_chr %:% z("A")
# z <- 1L
# #> Error:
# #> ! Attempted to assign a mistyped value to `z`.
# #> x `<value>` must be a bare <character>, not a bare <integer>.
# #> i Run last_type() to get the expected type.

